// Build time dependencies for CoMiso

#define COMISO_QT4_AVAILABLE 0
#define COMISO_BLAS_AVAILABLE 1
#define COMISO_GMM_AVAILABLE 1
#define COMISO_SUITESPARSE_AVAILABLE 0
#define COMISO_SUITESPARSE_SPQR_AVAILABLE 0
#define COMISO_MPI_AVAILABLE 0
#define COMISO_HSL_AVAILABLE 0
#define COMISO_PETSC_AVAILABLE 0
#define COMISO_TAO_AVAILABLE 0
#define COMISO_IPOPT_AVAILABLE 0
#define COMISO_MUMPS_AVAILABLE 0
#define COMISO_METIS_AVAILABLE 0
#define COMISO_TAUCS_AVAILABLE 0
#define COMISO_GUROBI_AVAILABLE 0
#define COMISO_ARPACK_AVAILABLE 0
#define COMISO_CPLEX_AVAILABLE 0
#define COMISO_Eigen3_AVAILABLE 1



